apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-argocd-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-argocd-application
    spec:
      containers:
      - name: app-argocd-basic-container
        image: jeongsujin/app-with-argocd:latest
       #imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8080
