apiVersion: v1
kind: Service   
metadata:
  name: app-argocd-basic-service
spec:
  selector:
    app.kubernetes.io/name: app-argocd-application
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31080
    port: 8080
    targetPort: 8080
