apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-app
    spec:
      containers:
      - name: argocd-app-container
        image: jeongsujin/app-with-argocd:80f87854025c5930e44a27331801d53cfed993a0
       #imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8080
