apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-app
    spec:
      containers:
      - name: argocd-app-container
        image: jeongsujin/app-with-argocd:12e94531e65a5b57e23dcaebf74ccae9b2fd4171
       #imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8080
